<h2 style="color:green" align="center">Machine Learning With Python: Save And Load Trained Model</h2>

In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [2]:
df = pd.read_csv("homeprices.csv")
df

area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

newmodel = linear_model.LinearRegression().fit(df[['area']],df.price)

In [3]:
model = linear_model.LinearRegression() # call linear regression model
model.fit(df[['area']],df.price) # training ( data, result)

LinearRegression()

In [4]:
model.coef_

array([135.78767123])

In [5]:
model.intercept_

180616.43835616432

In [12]:
price = model.coef_ * area + intercept 

NameError: name 'area' is not defined

In [6]:
model.predict([[5000], [2000], [3000]]) # area = 5000  , price = ? 

array([859554.79452055, 452191.78082192, 587979.45205479])

In [7]:
model.score(df[["area"]], df.price)

0.9584301138199486

<h3 style='color:purple'>Save Model To a File Using Python Pickle</h3>

In [9]:
import pickle  # .pickle extension model , h5. or .json,  games or programs.exe

In [10]:
with open('model_pickle','wb') as file: # write binary 
    pickle.dump(model,file) # put model into file

<h4 style='color:purple'>Load Saved Model</h4>

In [11]:
with open('model_pickle','rb') as file: # read binary 
    ourModel = pickle.load(file) # model is loaded into : ourModel  

In [12]:
ourModel.coef_

array([135.78767123])

In [13]:
ourModel.intercept_

180616.43835616432

In [14]:
ourModel.predict([[5000]])

array([859554.79452055])

<h3 style='color:purple'>Save Trained Model Using joblib</h3>

In [14]:
from sklearn.externals import joblib

TypeError: an integer is required (got type bytes)

In [15]:
import sklearn
sklearn.__version__

'0.24.2'

In [16]:
import joblib

In [17]:
joblib.dump(model, 'model_joblib') # model name

['model_joblib']

In [18]:
def savemodel(model, modelname):
    import joblib
    joblib.dump(model, modelname)

<h4 style='color:purple'>Load Saved Model</h4>

In [19]:
mj = joblib.load('model_joblib')

In [20]:
mj.coef_

array([135.78767123])

In [21]:
mj.intercept_

180616.43835616432

In [22]:
mj.predict([[5000]])

array([859554.79452055])