In [ ]:
70% dog   
30% cat  
accuracy : 0% 

    
70% train 
30% test 


70% 30% test , left train 


70% (40% , 30%)


train 1 2 3 4 5 6 7 
test  8 9 10 

train 1 2 3 4 8 9 10 
test 5 6 7

train 4 5 6 7 8 9 10 
test 1 2 3 


30% testing : 70% dog , 30% cat  
10 pictures : 7 dog, 3 cat  

<h1 style='color:blue;' align='center'>KFold Cross Validation Python Tutorial</h2>

In [1]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits
import matplotlib.pyplot as plt
digits = load_digits()

In [2]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(digits.data,digits.target,test_size=0.3)

**Logistic Regression**

In [3]:
lr = LogisticRegression(solver='liblinear',multi_class='ovr')
lr.fit(X_train, y_train)
#lr.score(X_train, y_train) # training accuracy
lr.score(X_test, y_test) # testing accuracy

0.9685185185185186

**SVM**

In [4]:
svm = SVC(gamma='auto')
svm.fit(X_train, y_train)
svm.score(X_test, y_test)

0.20555555555555555

**Random Forest**

In [5]:
rf = RandomForestClassifier(n_estimators=40)
rf.fit(X_train, y_train)
rf.score(X_test, y_test)

0.9740740740740741

In [6]:
import joblib
joblib.dump(rf, "randomforest model")

['randomforest model']

<h2 style='color:purple'>KFold cross validation</h2>

**Basic example**

In [6]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=3) # k = 3 
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [7]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]): # 9 : 30%  
    print(train_index, test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


**Use KFold for our digits example**

In [8]:
def get_score(model, X_train, X_test, y_train, y_test):
    model.fit(X_train, y_train)
    return model.score(X_test, y_test) # caclulate accuracy of test data 

In [9]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=3)

scores_logistic = []
scores_svm = []
scores_rf = []

for train_index, test_index in folds.split(digits.data,digits.target): # digits.data = x , digits.target = y 
    X_train, X_test, y_train, y_test = digits.data[train_index], digits.data[test_index], \
                                       digits.target[train_index], digits.target[test_index]
    scores_logistic.append(get_score(LogisticRegression(solver='liblinear',multi_class='ovr'), X_train, X_test, y_train, y_test))  
    scores_svm.append(get_score(SVC(), X_train, X_test, y_train, y_test))
    scores_rf.append(get_score(RandomForestClassifier(n_estimators=40), X_train, X_test, y_train, y_test))

In [10]:
scores_logistic # print score of each training of logistic regression model 

[0.8948247078464107, 0.9532554257095158, 0.9098497495826378]

In [11]:
scores_svm # print score of each training of support vector machine model 

[0.9649415692821369, 0.9799666110183639, 0.9649415692821369]

In [12]:
scores_rf # print score of each training of Random forest model 

[0.9282136894824707, 0.9499165275459098, 0.9265442404006677]

<h2 style='color:purple'>cross_val_score function</h2>

In [13]:
from sklearn.model_selection import cross_val_score

**Logistic regression model performance using cross_val_score**

In [14]:
cross_val_score(LogisticRegression(solver='liblinear',multi_class='ovr'), digits.data, digits.target,cv=3) # train 3 times 

array([0.89482471, 0.95325543, 0.90984975])

**svm model performance using cross_val_score**

In [15]:
cross_val_score(SVC(), digits.data, digits.target,cv=5)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

**random forest performance using cross_val_score**

In [16]:
cross_val_score(RandomForestClassifier(n_estimators=100),digits.data, digits.target,cv=3)

array([0.93489149, 0.95325543, 0.92654424])

In [17]:
model = cross_val_score(RandomForestClassifier(n_estimators=20),digits.data, digits.target,cv=3)

In [18]:
model

array([0.92988314, 0.94657763, 0.9115192 ])

cross_val_score uses stratifield kfold by default

<h2 style='color:purple'>Parameter tunning using k fold cross validation</h2>

In [19]:
scores1 = cross_val_score(RandomForestClassifier(n_estimators=10),digits.data, digits.target, cv=10)
print(scores1)
np.average(scores1) # i can depend on this accuracy 

[0.91111111 0.94444444 0.87222222 0.88333333 0.93333333 0.93333333
 0.93333333 0.93854749 0.92178771 0.86592179]


0.9137368094351335

In [20]:
scores2 = cross_val_score(RandomForestClassifier(n_estimators=20),digits.data, digits.target, cv=10)
np.average(scores2)

0.9349068901303538

In [21]:
scores3 = cross_val_score(RandomForestClassifier(n_estimators=30),digits.data, digits.target, cv=10)
np.average(scores3)

0.9426660459342022

In [22]:
scores4 = cross_val_score(RandomForestClassifier(n_estimators=40),digits.data, digits.target, cv=10)
np.average(scores4)

0.9482340161390439

Here we used cross_val_score to
fine tune our random forest classifier and figured that having around 40 trees in random forest gives best result. 

<h2 style='color:purple'>Exercise</h2>

Use iris flower dataset from sklearn library and use cross_val_score against following
models to measure the performance of each. In the end figure out the model with best performance,
1. Logistic Regression
2. SVM
3. Decision Tree
4. Random Forest